planetary-social/planetary-ios

- go-ssb-bindings/ctrl.go
fixes `level=error where=ssbInviteAccept err=“no such column: key”` and made the errors more descriptive
> fix column name on authors table

- Planetary.xcodeproj/project.pbxproj
- Source/Controller/ManagePubsViewController.swift
- Source/Controller/RedeemInviteViewController.swift
- Source/Localization/Text.swift
- Source/Localization/en.lproj/Generated.strings
- Source/Settings/SettingsViewController.swift
- go-ssb-bindings/ctrl.go
Adds ability to redeem an invitation code and adds a screen that lists known pubs.
> Redeem invitations

- Source/App/AppController+BackgroundSync.swift
- Source/Controller/LaunchViewController.swift
- Source/GoBot/GoBot.swift
- Source/GoBot/ViewDatabase.swift
- UnitTests/ContentTests.swift
- go-ssb-bindings/api-ios.go
- go-ssb-bindings/ctrl.go
- go-ssb-bindings/go.mod
- go-ssb-bindings/go.sum
- go-ssb-bindings/vendor/go.cryptoscope.co/margaret/offset2/log.go
- go-ssb-bindings/vendor/modules.txt
In order to not present the user with a hung UI, i've changed the order of sycing and updating. This should present an interface which feels more up to date. It doesn't solve the underlying performance problems but it does make it so the user doesn't have to deal with them before they can start using the app. 
I think we can do a LOT more in terms of making the app feel faster by changing when and how things happen without even having to make them faster.
> Change loading order to give UI which works faster

- Source/GoBot/GoBot.swift
- Source/GoBot/ViewDatabase.swift
This isn't proper pagination yet.
It just disables the most expensive query, the _replies to threads I started_ (without a direct mention).
Follow and Mentions are working _okay_. Meaning, notification view loading time is now under a minute.
> quick-fix notifications

- CHANGELOG.md
- Resources/Info.plist
- Show spinning wheel when processing new messages.
- Issue with reply count different than replies shown.
- Avatars when mentioning someone were displayed incorrectly sometimes.
- Avatar disappearing when switching tabs.
> Release 0.9.14

- Planetary.xcodeproj/project.pbxproj
- Resources/FBTT.entitlements
- Source/App/AppDelegate+UniversalLink.swift
- Source/Controller/AboutViewController.swift
- Source/Localization/Text.swift
- Source/Localization/en.lproj/Generated.strings
- Source/Model/Identity+Link.swift
Problem: We don't have a way of sharing profiles to the world.
Solution: Enable universal links and provide urls for profiles.
> Add Universal Links to profiles

- Planetary.xcodeproj/project.pbxproj
- Shared/Extensions/UIViewController+Confirm.swift
- Source/API/API.swift
- Source/API/APIError+LocalizedError.swift
- Source/API/APIError.swift
- Source/App/AppError+LocalizedError.swift
- Source/App/AppError.swift
- Source/Controller/AboutViewController.swift
- Source/Controller/BlockedUsersViewController.swift
- Source/Controller/ChannelViewController.swift
- Source/Controller/ChannelsViewController.swift
- Source/Controller/DirectoryViewController.swift
- Source/Controller/HomeViewController.swift
- Source/Controller/LaunchViewController.swift
- Source/Controller/ManagePubsViewController.swift
- Source/Controller/NewPostViewController.swift
- Source/Controller/NotificationsViewController.swift
- Source/Controller/RedeemInviteViewController.swift
- Source/Controller/ThreadViewController.swift
- Source/Controller/UIViewController+Block.swift
- Source/Localization/Text.swift
- Source/Localization/en.lproj/Generated.strings
Problem: Some errors are not handled, for instance, if
posting an image fails we just dimiss the screen. This
doesn't help catching errors because it appears everthing
went fine.
> Add Error alerts in many places they were not handled

- CHANGELOG.md
- Resources/Info.plist
Added:
- New Planetary typeface.
- Share your profile link to the world.
- Loading animation for Notifications and Channels screens.
Fixed:
- Show alert dialogs when errors occur.
- Report handled errors.
> Release 0.9.16

- Resources/Info.plist
- Source/Analytics/AnalyticsEnums.swift
- Source/App/AppController+BackgroundSync.swift
- Source/App/AppDelegate+Analytics.swift
- Source/App/AppDelegate+Background.swift
- Source/App/AppDelegate+Push.swift
Problem: App was trying to schedule task that were never registered
in Info.plist
Solution: Add key to Info.plist and refactor a little bit.
> Fix issue with BGTaskSchedulerErrorDomain

- CHANGELOG.md
- Resources/Info.plist
Added:
- Sync when pulling down to refresh on the feed.
Fixed:
- Links not displayed properly in posts.
- Images looked like broken links in posts.
- Background sync not working.
> Release 0.9.17

- Source/Controller/LaunchViewController.swift
- Source/Localization/Text.swift
Problem: Login throws an error if user was already logged in.
Solution: Take into account that case in launch.
> Fix issue where login fails for no reason.

- CHANGELOG.md
- Resources/Info.plist
- Source/Localization/en.lproj/Generated.strings
Added:
- Automatically detect links in posts.
Fixed:
- Images not displayed in order in the gallery.
- Bug that prevented login for some users.
- But that prevented displaying posts with code blocks in iOS 12.
> Release 0.9.19

- Source/Localization/Text.swift
- Source/Localization/en.lproj/Generated.strings
- Source/Onboarding/Steps/DirectoryOnboardingStep.swift
> Add search to users you might know in Onboarding

- Source/App/AppDelegate+Background.swift
- Source/UI/AboutView.swift
Problem: While links are detected in a bio, links to mentions
are not.
Solution: Detect mentions to identities, blobs or messages.
> Detect mentions in bio

- Source/Controller/ChannelViewController.swift
- Source/Controller/ChannelsViewController.swift
- Source/GoBot/ViewDatabase.swift
- Source/Model/Hashtag.swift
- UnitTests/FeedFill.swift
I've updated the channels list to have more information and loading image for specific channels.
> tweaking channels list to show more info

- CHANGELOG.md
- Resources/Info.plist
Added:
- All new Explore tab that shows posts from your greater network.
- New sync/refresh strategy that should be better at having your feed up to date.
> Release 0.9.21

- Source/Bot/Analytics+Blob.swift
We've been dumping bad data in to mixpanel and this fixes it.
> fixing blob log message to mixpanel

- Source/GoBot/GoBot.swift
- Source/GoBot/ViewDatabase.swift
- UnitTests/FeedFill.swift
We were not showing follows correctly if you had more than 50... this fixes it buy adjusting the sql. Not a big change.
> Fix notifications so we show follows

- Source/GoBot/ViewDatabase.swift
> add support for displaying likes

- Scripts/go_install.sh
- Source/GoBot/ViewDatabase.swift
- go-ssb-bindings/streams.go
i hoped to fix the duplication issue in the last update of go-ssb but it's still there.
> just replace duplicate messages for now

- Source/GoBot/GoBot.swift
Fixed:
* Profile avatar for the current user now is loading and set correctly.
> fixing bug where we weren't showing the top bar profile icon 

- CHANGELOG.md
- Planetary.xcodeproj/project.pbxproj
- README.md
- Resources/Info.plist
Added:
- We preload some feeds when onboarding so you don't have to wait to see something.
- Blob loading spinner.
- Load blobs from cloud as fallback.
> Release 0.9.27

- Source/Bot/Bot.swift
- Source/FakeBot/FakeBot.swift
- Source/GoBot/GoBot.swift
- Source/GoBot/ViewDatabase.swift
- Source/Localization/Text.swift
- Source/Localization/en.lproj/Generated.strings
- Source/Localization/es-ar.lproj/Generated.strings
- Source/Localization/es-uy.lproj/Generated.strings
- Source/Localization/es.lproj/Generated.strings
- Source/UI/PeersView.swift
We used to show local and online peers but that data isn't accurate so i changed it so we now show when it's most recently synced.
> changing activity montior to show last sync time

- Source/Bot/BotStatistics.swift
- Source/GoBot/GoBot.swift
- Source/GoBot/GoBotInternal.swift
- UnitTests/GoBotTests.swift
- go-ssb-bindings/debug.go
> Last hash in repo stats

- CHANGELOG.md
- Resources/Info.plist
Added:
- Followers are sorted by name.
- You can now search among your followers by name or identity.
Fixed:
- Tooling and statistics to figure out why some users aren't seeing updates and syncs.
> Release 0.9.29

- Source/Controller/DiscoverViewController.swift
- Source/Controller/HomeViewController.swift
- Source/Extension/UIFont+Verse.swift
- Source/UI/SmallPostHeaderView.swift
> hide dates from explore tab

- Source/Localization/Text.swift
I started out with removing the superfluos 'is' in the "someone started following you" notification text and then got carried away...
> Fix minor grammar and typo things

- README.md
This simple change adds some basic information about Planetary IOS to the top of the README of this repo.
It's meant to guide people that aren't up-to-speed with the development efforts at Planetary to understand:
- What they are looking at
- Where to go for more info.
Apart from making this change (and to promote posting one's own links first) it would probably not be a bad idea to add the Moniker 
> An IOS app that doesn't keep your data in the cloud https://planetary.social/
To the top of the repo like so:
I also created a repository social preview image for you to use on this repo (while I was at it anyway) that is in line with the cut-out standards for these types of images:
If you want to you can add that here:
The source-file for this image (to do whatever you want with): …
> Add basic info about the project to the Readme

- README.md
Here are the steps I had to take to get the project building on my Mac. I thought this might be useful for other contributors. If this belongs somewhere else just let me know.
> Add environment setup steps to the README

- .github/workflows/main.yml
- Source/GoBot/ViewDatabase+Pagination.swift
- Source/UI/KeyValue/KeyValuePaginatedTableViewDataSource.swift
- UnitTests/GoBotOrderedTests.swift
> Fix cell placeholders

- Source/UI/AboutsMenu.swift
> Fix the autocomplete drawer never hiding after opening it

- Source/Controller/ThreadViewController.swift
> Fix reply button disappearing after posting a reply

- Source/Controller/AboutViewController.swift
> Fix crash when tapping share button on Profile page

- Planetary.xcodeproj/xcshareddata/xcschemes/Planetary.xcscheme
Accidentally committed in #427
> Change the default locale back to the system language for simulator builds

- Source/Localization/Text.swift
- Source/Localization/en.lproj/Generated.strings
- Source/Localization/es-AR.lproj/Generated.strings
- Source/Localization/es-UY.lproj/Generated.strings
- Source/Localization/es.lproj/Generated.strings
- Source/UI/PostCellView.swift
I don't like how PostCellView.swift looks like. It looks like it contains several "hacks" to make it work, and it is hard to test as the way it is. I thought about refactoring it in order to be able to test the like at least, but it seemed too much effort for something that can be reworked from scratch the next time we have something big to add to that screen instead of just changing the size of the emoji.
> update Likes messages

- README.md
This is a proposed new App Store description. It is informed by recent user research and aims to remove confusing language about where your data is stored, privacy, and rewarding content creators. It also tries to explain the value proposition of Planetary with out using technical terms like decentralization, peer-to-peer, identity, replication, etc. I tried to focus on _what_ Planetary offers and less about _how_ it does so technically.
I pulled a lot of the language from Linda's shared [Google doc](https://docs.google.com/document/d/1iZzGvLOHrwYp4vWfx1EYA2Q-74XOvD5Fpn62GPEy3ZM/edit#). I also took the phrase "passes data from friend to friend" from [scuttlebutt.nz](https://scuttlebutt.nz/about/). I really love this phrase because it describes the peer to peer decentralized nature of SSB …
> Update appstore description

- GoSSB/Sources/api-ios.go
- GoSSB/Sources/blobs.go
- GoSSB/Sources/ctrl.go
- GoSSB/Sources/debug.go
- GoSSB/Sources/publish.go
- GoSSB/Sources/streams.go
- GoSSB/Sources/utils.go
Thanks to this panics should be visible in the logs.
> Log panics using the logger

- Source/UI/Buttons/ProgressButton.swift
> Disable ProgressButton until 100%

- Source/App/AppConfiguration.swift
- Source/Controller/Beta1MigrationCoordinator.swift
- Source/GoBot/GoBot.swift
- UnitTests/Beta1MigrationTests.swift
- UnitTests/GoBotIntegrationTests.swift
> Fix migration showing after deleting & reinstalling Planetary

- Source/App/AppDelegate+Push.swift
- Source/Bot/Bot.swift
- Source/Controller/Beta1MigrationCoordinator.swift
- Source/FakeBot/FakeBot.swift
- Source/GoBot/GoBot.swift
- UnitTests/Beta1MigrationTests.swift
- UnitTests/GoBotIntegrationTests.swift
> Suppress notifications during migration

- Source/Debug/DebugViewController.swift
- Source/UI/Buttons/EditPostButton.swift
- Source/UI/Buttons/RelationshipButton.swift
- Source/UI/ThreadInteractionView.swift
This will help us get logs from macos users. We just needed to set the sourceView before presenting UIActivityController.
> Fix share sheets showing off screen on macos

- Shared/Extensions/Date+Elapsed.swift
> Add year to dates in the notification page

- Source/Controller/Beta1MigrationCoordinator.swift
> Load migration progress bar faster

- GoSSB/Sources/api-ios.go
Seems to fix #581. What could go wrong?
> Don't wait on indexes when starting up GoBot

- Source/GoBot/FeedStrategy/PostsAlgorithm.swift
- UnitTests/FeedStrategyTests.swift
> Hide blocked posts from the discover feed

- Source/Model/MissionControlCenter.swift
This is a test to see if it reduces cpu usage.
> Only change connection with peers every 2 minutes instead of 30 seconds

- Source/Cache/BlobCache.swift
I learned from watching some WWDC videos that `Task { ... }` runs the task on the same actor that it was called from. The `BlobCache` functions are mostly called from UIViews and view controllers which means that they usually start on the Main Actor.  This updates the BlobCache to use `Task.detached { ... }`, which means it should block the Main Actor a little less.
> Use Task.detached instead of Task.init in BlobCache

- CHANGELOG.md
- Source/UI/FloatingRefreshButton.swift
> Fix FloatingRefreshButton shadow

- Source/Localization/ExportStrings.swift
- Source/Localization/af-ZA.lproj/Generated.strings
- Source/Localization/ar-SA.lproj/Generated.strings
- Source/Localization/ca-ES.lproj/Generated.strings
- Source/Localization/el-GR.lproj/Generated.strings
- Source/Localization/es-AR.lproj/Generated.strings
- Source/Localization/es.lproj/Generated.strings
- Source/Localization/fi-FI.lproj/Generated.strings
- Source/Localization/he-IL.lproj/Generated.strings
- Source/Localization/hu-HU.lproj/Generated.strings
- Source/Localization/ja-JP.lproj/Generated.strings
- Source/Localization/ko-KR.lproj/Generated.strings
- Source/Localization/no-NO.lproj/Generated.strings
- Source/Localization/pl.lproj/Generated.strings
- Source/Localization/ro-RO.lproj/Generated.strings
- Source/Localization/sr-SP.lproj/Generated.strings
- Source/Localization/sv-SE.lproj/Generated.strings
- Source/Localization/tr-TR.lproj/Generated.strings
- Source/Localization/vi-VN.lproj/Generated.strings
Now it matches the one that Crowdin uses so it should stop opening pull requests when nothing has changed.
> Fix the header in Generated.strings

- Source/Localization/Text.swift
Changed any instance in Text.swift of "Block" to "Ignore" and added "This will be publicly visible" to the block confirmation.
> Address #630 (Block/Ignore)

- Frameworks/GoSSB.xcframework/Info.plist
- Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
- Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
- GoSSB/Sources/go.mod
- GoSSB/Sources/go.sum
See https://github.com/planetary-social/ssb/commit/c7dc092193fc4cd3bb1c563ee9c1c6556582d253.
> Always recurse to process followees of people we follow

- CHANGELOG.md
- Source/App/AppDelegate+Push.swift
- Source/Controller/NotificationsViewController.swift
- Source/GoBot/ViewDatabase.swift
> Fix notification badges

- Frameworks/GoSSB.xcframework/ios-arm64/Headers/GoSSB.h
- Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
- Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/Headers/GoSSB.h
- Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
- GoSSB/Sources/include/GoSSB.h
- GoSSB/Sources/raw.go
> Add a function which returns raw messages to the bindings

- CHANGELOG.md
- Source/Controller/MenuViewController.swift
- Source/GoBot/GoBot.swift
Fixes the profile pic and name section in the side menu being empty when the user had not set a name.
> Fix the empty profile section in the side menu 

- CHANGELOG.md
- Source/Controller/ContentViewController.swift
- Source/Onboarding/OnboardingViewController.swift
- Source/Onboarding/Steps/PhotoOnboardingStep.swift
Fixes #844 and #805. Don't ask me why because I don't know.
> Fix onboarding hang

- CODE_OF_CONDUCT.md
- Source/Controller/NewPostViewController.swift
- Source/UI/PostTextEditorView.swift
Fixed another case of #868. It was hard to reproduce the bug in the first place, so I'm not 100% sure this fixes it, but I'm fairly confident it does.
> Fix another draft race

- CHANGELOG.md
- Source/GoBot/ViewDatabase.swift
> Add another index to speed up the home feed

- Source/App/AppController.swift
> Shake to debug 2

- CONTRIBUTING.md
Re: https://github.com/planetary-social/planetary-ios/pull/1014#discussion_r1051136846
> Add note about direct editing of Generated.strings

- .github/workflows/main.yml
I believe the two keys have to be different for the cache to be saved properly so we may just as well do this correctly.
> Fix Github Actions cache

- CHANGELOG.md
- Source/GoBot/GoBot.swift
- Source/Model/Address.swift
> Publish a RoomAliasAnnouncement when an alias is registered

- .codacy.yml
> add codacy configuration file

- Source/Bot/Bot.swift
- Source/Debug/AppConfigurationViewController.swift
- Source/FakeBot/FakeBot.swift
- Source/GoBot/GoBot.swift
- Source/GoBot/GoBotInternal.swift
- Source/GoBot/GoBotViewController.swift
Closes #1142 
It also removes all swiftlint warnings in GoBotViewController
> refactor needsViewFill to largestKnownRxSeq

- Source/UI/BotMigrationView.swift
> Show Start Using Planetary button on iPhone SE

- CHANGELOG.md
- Source/Controller/ThreadViewController.swift
> Alert user if some error ocurred while replying to a post

- CHANGELOG.md
- Source/GoBot/ViewDatabase.swift
> Fix an issue where an error alert was shown when displaying an unknown identity

- Analytics/Sources/Delivery/Analytics+Bot.swift
- Analytics/Tests/Delivery/AnalyticsTests.swift
- Frameworks/GoSSB.xcframework/ios-arm64/Headers/GoSSB.h
- Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
- Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/Headers/GoSSB.h
- Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
- GoSSB/Sources/include/GoSSB.h
- GoSSB/Sources/utils.go
- Source/App/AppController.swift
- Source/Bot/NSNotification+Bot.swift
- Source/GoBot/GoBot.swift
- Source/GoBot/GoBotInternal.swift
- Source/GoBot/GoBotViewController.swift
- Source/GoBot/ViewDatabaseError+LocalizedError.swift
- Source/GoBot/ViewDatabaseError.swift
- UnitTests/GoBotReproductionHelper.swift
> Remove ssbHealRepo and ssbOffsetFSCK

- Frameworks/GoSSB.xcframework/Info.plist
- Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
- Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
- GoSSB/Sources/bindings/bindings.go
- GoSSB/Sources/ctrl.go
- GoSSB/Sources/go.mod
- GoSSB/Sources/go.sum
944538c372e3 -> 9c687fa67f45
Commits:
- edbc2fe5e2b0833f2a250ac627734ad37e426367 Remove commented out code
- 98708b4bd979b411f3a33b9a845924a69d870930 Don't needlessly query contacts storage
- 250ab8b3f65828f94b302bce29ead1729ceaa095 Pass contexts as arguments instead of storing them
- 3cc924d98ba1f6a6cf4d9a6d424db46e1ba6ee3a Peek messages before verifying them
- 7fb5d5e3c6111d5da017183f89dc60d4ac15140b Try to persist more often to avoid sorting
- af41efae006d16965f14dc0b8368ed881d087d72 Only parse looking for blobs if there is a reason to
- f1a64f47fad2d93e492bd14c4ae907630722f97d Progressively build social graph
- 9c687fa67f45c6fcf98f95a363f57fbc97c475fc Cleanup less often
> Bump github.com/planetary-social/scuttlego

- Analytics/Sources/Delivery/Analytics+Conversions.swift
- Analytics/Tests/Delivery/AnalyticsTests.swift
- Source/Controller/NewPostViewController.swift
- Source/Controller/ThreadViewController.swift
> Track post and reply character counts in analytics

- CHANGELOG.md
- Source/Bot/Bot.swift
- Source/FakeBot/FakeBot.swift
- Source/GoBot/GoBot.swift
- Source/UI/Identity/RelationshipButton.swift
Fixes #1236 
It should be fine, but lets test it because the whole thing is a bit confusing if we don't pay attention. I left the solution in the issue I created.
> Solve confusing join button

- Source/UI/Identity/IdentityHeaderView.swift
My project doesn't compile for some reason, does this make any sense?
> Fix compilation errors
