planetary-social/planetary-ios

Source/Onboarding/Onboarding.swift

Problem: Phone verification is disabled in the app. However,
the hardcoded phone number doesn't have the country code so
in a non-us machine it fails when validating the number.
Solution: Disable phone number validation.

Disable phone number validation

---

Source/Controller/HomeViewController.swift

Problem: A notice is shown when there aren't posts in the home screen. However, it
doesn't disappear if the user post a new post.
Solution: Set table view background view to nil when there are posts.

Fix issue with no post notice in Home screen

---

go-ssb-bindings/ctrl.go
go-ssb-bindings/streams.go

I introduced two small bugs in #3.
* This makes `bot.refresh()` much faster since we don't need to marshal > copy > unmarshal all those messages.
* I forgot **not** to skip about and contact messages since these are always needed
It runs into a `database locked` problem. I need to re-write it so that it batches it's connect updates at the end of the loop as I cant hold a transaction lock for the whole connect loop process. For now it just logs those and keeps on connecting.

hotfix sync and old abouts

---

Scripts/go_install.sh
Source/GoBot/GoBot.swift
Source/GoBot/GoBotInternal.swift
Source/Model/Identities.swift

* downgrade to go1.13.8 (i think the new stuff in 14 is causing the interface scroll lag/jitter)
* `bot.disconnectAll` on resume (to save ram when going in the background)
* don't make connections on startup (might need to wait for a timer but is less cpu and network heavy, also going back and forth makes lots since there is no cap yet.)
* update pub addresses
ps: you need to remove `go-ssb-bindings/.goroot` for it to update the toolchain correctly. Patch for a version check pending.

some quick improvments

---

Source/GoBot/GoBotInternal.swift

This cleans up the list of planetary pubs. All use dedicated domain names now. There were some inconsistencies in the ports, too.

New pubs list

---

Source/GoBot/GoBot.swift
Source/GoBot/GoBotInternal.swift
go-ssb-bindings/ctrl.go

This should fix the need to manually tap "Sync" in the debug menu.
In some cases `dialSomePeers()` did nothing, especially during onboarding.

fix syncing

---

Source/UI/PostCellView.swift

Problem: If you tap on a link in a post while scrolling
the app opens the link instead of allowing the user continue
scrolling through the feed.
Solution: Remove link decection on text views because they
are already handled by the tap gesture.

Fix links being opened while scrolling

---

Source/App/AppController+BackgroundSync.swift
Source/GoBot/GoBot.swift

We wait a bit so that the UI can finish loading, though.
This should get us updates right after the app starts. Still looking for why the background timer doesnt work anymore.
ps: sorry for the noisy diff but this was indented wrong...

add dialing peers after login was successfull

---

Deprecated/Channel.swift
Shared/Extensions/String+HashtagSubstrings.swift
Source/GoBot/ViewDatabase.swift
Source/Model/Blob.swift
Source/Model/Hashtag.swift
Source/Model/Mention+NSAttributedString.swift
Source/Model/Mention.swift
Source/Model/Post+Blob.swift
Source/Model/Post.swift
UnitTests/ContentTests.swift
UnitTests/FeedFill.swift
UnitTests/PostWithHashtags.json

This uses `mentions: [ {link: #tag1}, {link: #tag2}]` together with the markdown text to indicate which hashtags a post should belong to.
For this I had to make `name: String` optional on the `Hashtag` type.
Need to find the regexp responsible for striping of dashes. Afterwards this is good to go.

use mentions for channels

---

Planetary.xcodeproj/project.pbxproj
Source/GoBot/ViewDatabase.swift
UnitTests/ContentTests.swift
UnitTests/GoBotTests.swift
UnitTests/PostsWithMentions.json

we don't name name blobs right now but others might.
Before we called all attachments `blob`, this seemed wasteful but i didn't cover all the areas when making name optional.

fix empty name from blobs

---

Source/Controller/ThreadViewController.swift
Source/GoBot/ViewDatabase.swift

Problem: We show the reply count that is different that the replies
we show because a reply can be a post, a vote, or anything, but we
just show posts.
Solution: Filter posts when calculating the number of replies.

Fix issue with reply count different that replies shown

---

Planetary.xcodeproj/project.pbxproj
Source/Controller/AboutViewController.swift
Source/Controller/LaunchViewController.swift
Source/Model/Notification+About.swift
Source/UI/AvatarButton.swift

Problem: When switching tabs, avatar disappears if the bot takes too
long to return an about because we are asking the current about each
time.
Solution: Use cached about we have in memory and update it when
editing the profile.

Fix issue with avatar disappearing when switching tabs

---

Source/UI/AboutCellView.swift
Source/UI/AboutsMenu.swift

Problem: When typing a mention @something sometimes an avatar is not
correct because the cell doesn't prepare for reuse.
Solution: Reset the view when prepareForReuse is called.

Fix mentions' avatar are wrongly displayed

---

Source/GoBot/GoBot.swift

Problem: App crashes when repair fails because we are sending to Mixpanel
a Error instance which is not supported.
Solution: Send the description (String) instead.

Fix crash when repair fails

---

Source/Analytics/Log.swift
Source/Analytics/NullLog.swift
Source/Analytics/OSLog.swift
Source/App/AppDelegate.swift
Source/Debug/DebugViewController.swift

Problem: A user reports logs not appearing for downloading
and an iPad user even crashing.
Solution: Consider popover controller in iPad and make sure
DDLog is configured at start.

Fix issue with downloading logs

---

Source/Controller/ThreadViewController.swift
Source/UI/MentionTextViewDelegate.swift
Source/UI/PostButtonsView.swift

Problem: When the keyboard is undocked, normal notifications are
not sent so post button is never shown.
Solution: Use UITextViewDelegate didBeginEditing and didEndEditing
to show/hide the post button.

Fix post button not appearing when keyboard is undocked

---

Configs/Environment.swift
Configs/Shared.debug.xcconfig
Source/Analytics/MixpanelAnalytics.swift
Source/App/AppController+Push.swift
Source/CrashReporting/CrashReporting.swift

Problem: While we have a way of not using Mixpanel, en empty key is still
required to be in the configs file. Also, Mixpanel is being used in Debug config.
Solution: Configure Mixpanel only if key is present and remove the key from Debug config.

Prevent using Mixpanel if not configured and if in debug

---

CHANGELOG.md
Resources/Info.plist

Fixed:
- Post button not appearing when undocking the keyboard.
- Crash when downloading logs in iPad.
- Empty log when downloading logs.
- Crash when database repair fails.
- Bad wording for number of replies in a post.

Release 0.9.15

---

Source/Controller/ChannelsViewController.swift
Source/Controller/ContentViewController.swift
Source/Controller/HomeViewController.swift
Source/Controller/NotificationsViewController.swift

Problem: Nothing appears when first loading notifications and channels.
Solution: Add same loading graphic animation when loading the feed.

Loading graphic for notifications and channels tabs

---

go-ssb-bindings/api-ios.go
go-ssb-bindings/ctrl.go

also resets all the addresses when none can be used anymore.
Even with WAL mode I was getting `database locked` errors when not using transactions. This should do the trick.

fix updating of peers table

---

Source/Bot/Bot+AppConfiguration.swift

Problem: Bot is not logging in when syncing in the background.
Solution: Remove requirement to have a hmac key.

Fix issue when attempting to background sync

---

Source/Controller/HomeViewController.swift

Problem: When pulling down to refresh in the feed doesn't
triggers sync so that the user has to send the app to background
for that to happen.
Solution: Add sync when pulling down to refresh (but not when
loading the app the first time).

Sync bot when pulling down to refresh on the home screen

---

CHANGELOG.md
Resources/Info.plist

Added:
- Complete support of CommonMark (an unambiguous spec of Markdown)
Fixed:
- Minor bugfixes regarding the use of Scuttlebutt.

Release 0.9.18

---

Source/Bot/Bot+Publish.swift

Problem: When publishing a post, blobs are processed asynchronously
one by one so the order is lost.
Solution: Use a map to keep track of the original index.

Fix issue where attached images are not in the right order

---

Source/Markdown/String+Markdown.swift
UnitTests/MarkdownTests.swift

Problem: User unaware of markdown format could just type a link
without paranthesis.
Solution: Detect those cases and display a link in the post.

Decode unformatted links in posts

---

Source/Extension/UIFont+Verse.swift

Problem: We use monospaced system font for displaying code in posts
but this is only supported in iOS 13 and onwards.
Solution: Use normal font for code in iOS 12 and below.

Fix crash when displaying a post with codeblock in iOS 12

---

Source/Bot/Bot.swift
Source/CrashReporting/BugsnagCrashReporting.swift
Source/Debug/DebugViewController.swift
Source/FakeBot/FakeBot.swift
Source/GoBot/GoBot.swift
Source/Support/ZendeskSupport.swift

Problem: GoBot logs are not used.
Solution: Attach GoBot logs to Share logs in Debug, to Bugsnag crash reports
and to Zendesk tickets.

Send GoBot logs

---

Source/Bot/Bot.swift
Source/Bot/SyncOperation.swift
Source/FakeBot/FakeBot.swift
Source/GoBot/GoBot.swift

Problem: App crashes when receiving a notification in the background
because sync asserts that is being run in the main thread.
Solution: Remove the assertion and make syncNotifications work
similar to sync.

Fix crash in notifications' sync

---

Source/Cache/BlobCache.swift
Source/GoBot/GoBotInternal.swift

If we don't have the local blob we request it over ssb then download it via google cloud storage as as a fallback.  Seems to work. Reduces blank images we see.

add fallback to using cloud hosted blobs

---

Planetary.xcodeproj/project.pbxproj
Source/GoBot/ViewDatabase.swift
UnitTests/FeedFill.swift
UnitTests/Feed_example.json
UnitTests/GoBotTests.swift

This reverts PR #117. Just replacing it in the messages table meant that
the the more specialzed messages (viewdb L1631 ff) were still inserted.

hotfix duplication

---

Source/UI/PostCellView.swift

Our icon for liking is a heart, but we don't display it that way, instead we display thumbs up / down. So it's fixed, now we use ❤️&💔

fixing amanda's request that we use ❤️&💔

---

Source/GoBot/ViewDatabase.swift
Source/UI/AvatarImageView.swift

So it turns out that sorting the the feed content by claimed at takes like 1.6 seconds vs using msg_id to sort which is 20ms. Basically using msg id means we're using when it arrived in the device. I know some folks don't think thats a better expience, but i'm making the switch because it's like 80 times faster.

changing feed loading to use msg_id instead of claimedAt for sorting

---

Source/Markdown/MarkdownStyler.swift

Makes it it much easier to read longer posts by adding more space between paragraphs.

spacing between paragraphs

---

Planetary.xcodeproj/project.pbxproj
Source/Controller/NewPostViewController.swift
Source/Controller/ThreadViewController.swift
Source/Localization/Text.swift
Source/Localization/en.lproj/Generated.strings
Source/UI/PostButtonsView.swift
Source/UI/PostReplyView.swift
Source/UI/PostTextEditorView.swift
Source/UI/ReplyTextView.swift

Here comes basic Markdown previewing. I moved stuff around as I saw fit - there are a few things I would like your opinion on:
- The mention delegate needs direct access to the `UITextView`, therefore I integrated it into `PostEditorTextView`. I'd rather kept it outside for better separation but pulling it out seems too involved.
- The `PillButton` looks almost disabled to me when `isSelected = false`. However I wanted to visually differentiate the preview button from the post button. Not quite happy with the current setup, do you have better ideas?
- I haven't come up with a nice way to communicate the Markdown capability now that the "Markdown supported" label is gone. Having "Preview Markdown" as the button caption is way too long already, not even thinking about a German translation. …

Add Markdown preview during post creation

---

Source/Extension/UICollectionView+Verse.swift

Currently, if you tap the tab bar icon for the Discover page (when already on that view) to trigger a scroll to the top, the left margin gets messed up.
Looks like `scrollToTop()` was setting the content offset to `0` despite it being set to `5` on the view itself. This uses the defined value from the collectionView instead, as it already did for the y offset. 
Screen recording of bug:
https://user-images.githubusercontent.com/1018145/107459081-3f40fa00-6b0a-11eb-8c66-041496e3a133.mov

Fix inset misalignment from scrollToTop on UICollectionView

---

Shared/Layout/UIEdgeInsets+Layout.swift
Source/UI/PostTextEditorView.swift

I think this addresses #202. (and potentially #209, but there's not much detail there.)
Content is currently being cut off on the right and bottom edges of the new post view. 
I think that's because `UIEdgeInsets.default` had negative values set for `right` and `bottom`. I solved this by modifying that `.default` itself, as this is the only place that it's being used. (Well, it's also used once in `addSpacerView()`, but that only grabs the `UIEdgeInsets.default.top` value, which remains unchanged.) If there's any other plans for using that default, this change can be done elsewhere. :) 
The second thing is switching from `contentInset` to `textContainerInset` on the UITextView. Without this switch, it gets all bouncy and crazy without the negative margins when text is modified. But I …

Tweak insets on new post editor to prevent content running off screen 

---

Planetary.xcodeproj/project.pbxproj
Shared/Extensions/UIViewController+Alert.swift
Source/App/AppController+URL.swift
Source/Bot/Bot.swift
Source/Bot/Operations/RedeemInviteOperation.swift
Source/Controller/RedeemInviteViewController.swift
Source/FakeBot/FakeBot.swift
Source/GoBot/GoBot.swift
Source/GoBot/ViewDatabase.swift
Source/Localization/Text.swift
Source/Localization/en.lproj/Generated.strings
Source/Model/About.swift
Source/Model/Identifier.swift
Source/Model/Star.swift
Source/UI/Buttons/FollowButton.swift
UnitTests/ViewDatabaseTests.swift

#272 this prevents go-ssb from locking for 70 seconds on a bad pub TCP connection by trying our to make our own TCP connection to pubs first. I also did some refactoring to show a nicer error message when pub invitation redemption fails.

Work around pub invitation lock

---

Planetary.xcodeproj/xcshareddata/xcbaselines/5308168421C46A52005C48ED.xcbaseline/188BAB62-50E9-4AEA-A97C-F3B7599AC7F7.plist
Planetary.xcodeproj/xcshareddata/xcschemes/Planetary.xcscheme
Source/GoBot/ViewDatabase.swift
UnitTests/Performance/ViewDatabasePerformanceTests.swift

#305 This removes the `db.transaction` wrapper in `ViewDatabase.fillMessages()`. While wrapping our writes to SQLite in a transaction gives a small (~6%) speed boost to the write operations, it creates an exclusive lock on the database, preventing any other reads or writes from taking place. By inserting rows individually instead of in a transaction, we allow readers to read from the database in between insertions. This is important when we are copying over large amounts of data from go-ssb, as a big write transaction can take more than 10 seconds. And it fits with our general strategy of using [SQLite as a cache layer](https://github.com/planetary-social/planetary-ios/blob/master/Architecture/0004-use-sqlite-as-a-cache.md) and optimizing it for read performance.

Fix SQLite write locking

---

.github/workflows/main.yml

@boreq this adds a Github Action to compile the Go code as part of our PR checks. I realized the Go wasn't actually being compiled in our current "Unit Tests" job, which is why the tests were passing on your other PR. Maybe this will help you test things on the `bump_version` branch. Feel free to click merge on this if you want to use it.

Add a job to compile GoSSB.xcframework on the CI server

---

.swiftlint.yml

This adds configuration parameters for SwiftLint to our repository. They still only run in Codacy, but instead of being configured in Codacy's web UI they will be in the repo. This gives us a few benefits:
- Changes to rules will have to go through PR review & discussion
- Less vendor lock-in with Codacy
- This is a first-step towards running SwiftLint locally on every build, something we would like to do someday.
I went pretty crazy enabling rules. I figured it would be easier to disable the ones we don't like rather than enable ones we think of in the future. So please view the rules list as a very fluid thing for the next month or two. So if any seem too annoying let's discuss. Does that sound good @martindsq?

Add swiftlint.yml

---

Resources/Info.plist

This adds a simple URL scheme that will allow us to reliably open the app from other apps, like Userlytics.

Add planetary:// as a URL scheme to open the app

---

GoSSB/Sources/api-ios.go

A while ago a mechanism which tries to filter accepted connections was
introduced in go-ssb. By defaut this mechanism accepts connections based on the
follow graph. This may make sense if go-ssb acts as a pub but makes little
sense if go-ssb runs on a phone as your social media profile node. After all as
a user I want people to connect to me and get my messages. My profile is
public.
On top of all of that the feature doesn't seem to work correctly. Even after I
followed my Patchwork identity the connections from/to Patchwork were still
being rejected.
This sets an authorizer which accepts all peer connections to mitigate this
problem.
Fixes #431.

Accept all peer connections

---

Source/Model/Mention+NSAttributedString.swift
UnitTests/AttributedStringTests.swift
UnitTests/GoBotIntegrationTests.swift

Closes #327
Converting a Mention to a NSAttributedString wasn't done properly. Check accepted answer [here](https://stackoverflow.com/questions/56470728/swift-nsattributedstring-emojis).

Fix issue when mentioning a profile with an emoji

---

Source/Bot/Bot.swift
Source/Bot/Operations/SendMissionOperation.swift
Source/Bot/Operations/SyncOperation.swift
Source/FakeBot/FakeBot.swift
Source/GoBot/GoBot.swift
Source/GoBot/GoBotInternal.swift
Source/GoBot/ViewDatabase.swift
Source/Model/MissionControlCenter.swift
Source/Model/Star.swift

No ticket for this. It's partly trying to fix some connection issues @rabble was seeing in TestFlight, and partly an experiment based on our latest findings in go-ssb. Changes include:
- Run SendMissionOperation every 30 seconds instead of 60 seconds. 
- Disconnect from peers before connecting to new ones.
- Pass the full list of all joined pubs to `Bot.sync()`. I thought `Bot.sync()` would actually tell go-ssb to connect to all the peers we passed it, but it actually has its own algorithm to pick a subset of the passed peers.
- Updated the names of some things and added doc comments.

Disconnect peers before connecting to new ones, and connect more often

---

CHANGELOG.md
Shared/Debug/DebugTableViewCell.swift
Shared/Debug/DebugTableViewController.swift
Source/Bot/Bot.swift
Source/Cache/BlobCache.swift
Source/Debug/DebugViewController.swift
Source/GoBot/GoBot.swift
UnitTests/GoBotIntegrationTests.swift
UnitTests/GoBotOrderedTests.swift
UnitTests/GoBotReproductionHelper.swift

As I was doing final QA on 1.1.0 (316) today I noticed that replication was not happening at all on a fresh install of Planetary. As I investigated it seemed that go-ssb was locking internally when `Bot.statistics` was called from multiple threads simultaneously. This would put go-ssb into a state where it wouldn't do anything else until you force quit the app.
This PR synchronizes access to the `Bot._statistics` variable, ensuring that we never hit this bug in go-ssb. I also got a main thread assertion failure in the BlobCache and fixed that as well.

Synchronize access to Bot.statistics

---

CHANGELOG.md
Source/Debug/AppConfigurationViewController.swift

I've found a problem that a secret in the configuration menu is shown wrong. You could see it on this screenshot:
So i've fixed it by changing a numberOfLines property. Now it looks like this:

Fixed numberOfLines for secret text label in debug menu

---

.swiftlint.yml
Planetary.xcodeproj/project.pbxproj
Source/App/AppConfiguration.swift
Source/Bot/Bot.swift
Source/Bot/Operations/JoinPlanetarySystemOperation.swift
Source/Bot/Operations/SendMissionOperation.swift
Source/Controller/ManagePubsViewController.swift
Source/GoBot/ViewDatabase.swift
Source/Onboarding/Onboarding.swift
UnitTests/AppConfigurationTests.swift

#485 This prevents us from auto joining Planetary system pubs if the user has created their identity by adding their secret key in the debug menu. It does this by adding a new `joinedPlanetarySystem` flag to `AppConfiguration`. System pubs are only auto-joined if this flag is set, and it is only set during onboarding. Right now it is always set if the user creates their identity in the onboarding flow, but in the future it will be easy to add a toggle in the UI that is bound to the flag. This would let users opt out of having the Planetary pubs auto-follow them.
I also fixed a bug where we were redeeming invitations to the system pubs multiple times. It wasn't hurting anything but it did create a lot of noise.
Also I tweaked the sync algorithm so that the app will connect to the Planetary …

Fix key import forking feeds

---

Planetary.xcodeproj/project.pbxproj
Scripts/swiftlint.sh
Scripts/swiftlint_diffonly.sh

This PR adds a "Run swiftlint" in the main target that executes SwiftLint just in the modified files as documented in https://github.com/realm/SwiftLint/issues/413.
The script itself is in Scripts/swiftlint.sh just in case we want to run SwiftLint from the console as well, or from a pre-commit hook. 
It doesn't fail if SwiftLint is not installed, but it doesn't succeed if SwiftLint was not installed using HomeBrew. I think both of us use brew so it won't be a problem for now, but we might need to change the SWIFT_LINT=/opt/homebrew/bin/swiftlint part in the future.

Add swiftlint as a Planetary target build phase

---

Source/App/AppController+Progress.swift
Source/Controller/AboutViewController.swift
Source/UI/ImagePicker.swift

This fixes a little bug I found while hunting down some blob issues. We were trying to present error alerts on top of the image picker which didn't work and the UI would freeze. I noticed it because I was getting forked feed protection errors when trying to set an image for my test profile. You may need to delete and reinstall the app in order to reproduce.
I also started showing a loading indicator again in this case. The code to show it was commented out for some reason. I also shortened the "grace" time for loading indicators because it felt really long.

Fix showing alert if saving photo fails on AboutViewController

---

Scripts/swiftlint_diffonly.sh

The new swiftlint build phase tries to change some of our delegates to `weak` and causes compiler errors. Maybe we need to refactor or maybe we just need to disable this swiftlint rule. But for now I will just disable the "swiftlint autocorrect" command.
Not going to wait on a review for this one since it is breaking compilation on `main`.

Disable swiftlint autocorrect

---

Source/Onboarding/Onboarding.swift
Source/Onboarding/Steps/DoneOnboardingStep.swift
Source/Onboarding/Steps/SplashOnboardingStep.swift

Just something I noticed while looking at our analytics this morning. The start event and end events were both firing in the middle of onboarding, not at the start and end.

Fix Onboarding start and end events

---

Planetary.xcodeproj/project.pbxproj
Source/Bot/Bot.swift
Source/Bot/Operations/ExitOperation.swift
Source/GoBot/GoBot.swift
UnitTests/Beta1MigrationTests.swift
UnitTests/GoBotIntegrationTests.swift
UnitTests/GoBotOrderedTests.swift

#514 The problem here was that we weren't waiting for the calls in `Bot.exit()` to finish executing before logging in again. I made it `async` and now things seem to work.

Fix beta1 migration tests

---

Source/Cache/BlobCache.swift

I noticed that sometimes fetching a blob from go-ssb fails with a message about "failing to pour to a closed sink". I think this happens when go-ssb tries to ask a peer for a blob but the peer has closed the connection on their end. This adds a simple exponential backoff retry algorithm to retry fetching the blob.

Add retry when blobWant fails

---

GoSSB/Sources/go.mod
GoSSB/Sources/go.sum
Scripts/go_install.sh

This fixes very slow replication that only happens on a real iOS device not the simulator. Don't know why.

Revert go version to 1.17.8

---

Source/Extension/UIPageControl+Verse.swift

This is just a tiny tweak that @Chardot asked for.

Remove gray background for page controls

---

Source/UI/ImagePicker.swift

This is a tweak I made for myself this weekend when I wanted to post some images from Planetary. I think it's a better experience than what we have in the App Store currently. There are many issues with the current cropping UI (#390 #317 #233). This PR simply removes the ability for users to crop their photos in Planetary. The photo is simply uploaded exactly as it is given from the photos app/camera.

Remove ability for user to crop image during selection

---

.swiftlint.yml
Source/Bot/BotStatistics.swift
Source/Debug/BotViewController.swift
Source/GoBot/GoBot.swift
Source/GoBot/ViewDatabase.swift
UnitTests/ViewDatabaseTests.swift

This adds back the 6 month limit for copying posts into SQLite. This should get the performance for most of the queries back to acceptable levels. I also filed #595 so we remember to revisit this in the future.

Add 6 month post limit

---

Source/GoBot/ViewDatabase.swift

This was just a little thing that has been really annoying after the migration. Replies to threads are sorted in the order they were received by go-ssb. This changes them to be synced by claimed time. Both have their problems, but claimed time seems better for the short term because in 99% of cases it keeps the conversation in order.

Sort replies by claimed date

---

Source/GoBot/FeedStrategy/RecentlyActivePostsAndContactsAlgorithm.swift
UnitTests/FeedStrategyTests.swift

This fixes a bug I found this morning in the "Recently Active Posts and Contacts" algorithm where a root post with no replies would be incorrectly sorted too far down. My SQL COALESCE statement needed to be outside of the subquery that gets the timestamp of the latest reply, not inside.

Fix Patchwork algorithm sorting

---

Source/Controller/Beta1MigrationCoordinator.swift

I just realized that the progress target was being calculated incorrectly in Beta1MigrationCoordinator. We need to count the messages within the last 6 months now, because we are computing progress based on the messages in SQLite and not Badger.
This would only be an issue for active users with accounts older than six months who would sit and wait for the migration bar to hit 100%, which probably isn't many users, but still definitely worth fixing.

Remove old messages from progress target

---

Source/Bot/Bot.swift
Source/Controller/ConnectedPeerListCoordinator.swift
Source/FakeBot/FakeBot.swift
Source/GoBot/GoBot.swift
UnitTests/Controller/ConnectedPeersCoordinatorTests.swift

This is a little optimization for the number of recently downloaded posts shown in the sidebar. The GoBot takes a long time to respond to `statistics()` calls these days. But we actually fetch the recently downloaded post count from SQLite, which doesn't take very long. This code bypasses `statistics()` to show the count more quickly after the menu is opened.

Make the recently downloaded post count load faster

---

Source/GoBot/FeedStrategy/PostsAndContactsAlgorithm.swift
Source/GoBot/FeedStrategy/RecentlyActivePostsAndContactsAlgorithm.swift
Source/UI/Buttons/PillButton.swift
Source/UI/ContactCellView.swift
Source/UI/ContactHeaderView.swift
Source/UI/ContactView.swift
UnitTests/GoBotOrderedTests.swift

- Fix block messages showing as follows #619
- Fix background color of hashtag label #620
- Show individual sections when they have finished loading instead of waiting for everything to load. This is not ticketed, but I noticed that the follow messages are taking a long time to load on my actual device, and I wanted to see if this makes it feel better. I think it does, but I'm not sure if this was an intentional design decision @martindsq so let me know.

Tweak follow messages

---

GoSSB/Sources/api-ios.go

Garbage collection is responsible for a large percentage of our CPU usage. This
pull request tries to revert GC settings to the default ones (collection once
newly allocated memory reaches 100% of previously allocated memory).

Make GC less aggressive

---

GoSSB/Sources/api-ios.go

Reverts planetary-social/planetary-ios#651
This change has caused frequent crashes for some of us and hasn't solved the energy usage problem, so I'm reverting it for our release build today.

Revert "Make GC less aggressive"

---

GoSSB/GoSSB.xcodeproj/project.pbxproj
Scripts/go_install.sh

The script will now check the installed Go version and if it is incorrect the
Go tools will be redownloaded. This should streamline our development process.
Fixes #541.

Detect incorrect Go version during builds

---

CHANGELOG.md
Source/Controller/ThreadViewController.swift
Source/UI/PostCellView.swift
Source/UI/PostHeaderView.swift
Source/UI/ThreadReplyView.swift

Replaces the time ago for messages in the home feed with the identity of the poster. This might not be right, but it does show a bit more of the underlying structure of ssb which is good and also makes the app less immediacy focused. 
This PR Resolves ticket #660

replace time ago in feed for messages with the poster's identity

---

.github/workflows/main.yml

I had an issue yesterday where git got into an inconsistent state and it was a pain to deal with. My understanding is that this happened because someone without `git lfs` installed committed to a file tracked by `git lfs`. This adds a simple CI job that should fail if it happens again.

Add git lfs fsck CI job

---

CHANGELOG.md
Source/Controller/ChannelsViewController.swift

This is a 5 minute tweak I made because I put a whole hashtag into the hashtags search box and it didn't work.

Filter the hashtag character out of the hashtag search box

---

CHANGELOG.md
Source/GoBot/FeedStrategy/PostsAndContactsAlgorithm.swift
Source/GoBot/FeedStrategy/RecentlyActivePostsAndContactsAlgorithm.swift
Source/UI/AvatarImageView.swift
Source/UI/ContactHeaderView.swift
Source/UI/ContactReplyView.swift
Source/UI/ContactView.swift
Source/UI/KeyValue/KeyValueTableViewCell.swift
UnitTests/FeedStrategyTests.swift

This fixes part of #708, the part where the cell was too tall. I tried to fix the issue with the skeleton view not overlapping all the text, but I couldn't get the SkeletonView library to behave, and I found an open issue in their repository: https://github.com/Juanpe/SkeletonView/issues/500. Since I had so much trouble I'm not going to try to add the new follow button Sebastian designed, I will just wait and do that when we rewrite this view in SwiftUI.

Fix layout issue in Contact cells where cell height was too large

---

Planetary.xcodeproj/project.pbxproj
Source/App/AppDelegate+Push.swift
Source/Bot/Operations/CountUnreadNotificationsOperation.swift
Source/Controller/NotificationsViewController.swift
Source/GoBot/GoBot.swift
Source/GoBot/ViewDatabase.swift
UnitTests/ReportTests.swift

- Before setting a report as read, we need to check if it alread read so we don't generate notifications for alread read reports. This query was a bit expensive, this PR makes it more lightweight by just querying the read status (not building the report object)
- When creating reports, a didCreateReport notification was generated for each one of them. This PR changes it so it generates one single notification.

Optimize read notification queries

---

Source/App/AppDelegate.swift

This will let us check the app version that users were running when the send us logs.

Log app version on launch

---

CHANGELOG.md
Source/Bot/Bot.swift
Source/Bot/Operations/RefreshOperation.swift
Source/Debug/AppConfigurationViewController.swift
Source/Debug/BotViewController.swift
Source/FakeBot/FakeBot.swift
Source/GoBot/GoBot.swift
UnitTests/GoBotIntegrationTests.swift
UnitTests/GoBotOrderedTests.swift
UnitTests/GoBotReproductionHelper.swift
UnitTests/Test Helpers/GoBotTestExtensions.swift

Fix case where tapping the Reset Forked Feed Protection button would hang. The issue is that if `fillMessages` skipped any messages we would report that it didn't finish syncing, and then the app would never finish syncing.

Fix Reset Forked Feed Protection button

---

Source/GoBot/GoBot.swift
Source/GoBot/GoBotInternal.swift
Source/GoBot/ViewDatabase.swift
UnitTests/ViewDatabaseTests.swift

Fixes #731 
This changes the way the ban list is applies. Before this PR, the list was downloaded on app launch, used to hide messages in SQLite, and then discarded. Now we save the list to the db, delete messages instead of hiding them, and prevent banned messages from ever being written to SQLite in `fillMessages`. We also keep track of when authors are unbanned so we start replicating with them again. Unbanning messages is still not supported.

New logic for applying the ban list

---

CHANGELOG.md
Source/Onboarding/OnboardingViewController.swift
Source/Onboarding/Steps/PhotoOnboardingStep.swift

Fixes an issue where bio screen in onboarding would freeze on iOS 15.6. By removing the bio onboarding screen.

Disable the onboarding bio step because it doesn't work on iOS 15.6

---

Source/Bot/Bot.swift
Source/Controller/AboutViewController.swift
Source/FakeBot/FakeBot.swift
Source/GoBot/GoBot.swift

when you view a profile, we tell gobot to refresh the feed of that profile. Even if you're not following the person or they are in your network.
This doesn't refresh the UI, that'd be nice but more work.

Trigger refresh on view profile

---

CHANGELOG.md
Source/GoBot/FeedStrategy/PostsAlgorithm.swift
Source/GoBot/KeyValue+ViewDatabase.swift
Source/GoBot/ViewDatabase.swift
Source/Model/KeyValue.swift
Source/UI/PostReplyView.swift

I got myself very confused this morning and thought the whole app was broken. It turns out that the thread view is just totally broken if the replies are from users without names. This fixes that by doing LEFT OUTER joins instead of LEFT INNER on the `about` table when loading replies, and tweaking the PostReplyHeader to handle this case.

Fix the thread view for users without names

---

Source/App/AppConfiguration.swift
Source/Bot/Operations/JoinPlanetarySystemOperation.swift
Source/Bot/Operations/SendMissionOperation.swift

This fixes the issue I found when doing final QA for 1.3.4. The JoinPlanetarySystem operation was adding operations to the same queue it was on, then tried to wait for that queue to be empty... which meant it was waiting on itself to finish. Who wrote this terrible code? It was me.

Fix a bug where the JoinPlanetarySystemOperation would hang

---

CHANGELOG.md
Frameworks/GoSSB.xcframework/Info.plist
Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/go.mod
GoSSB/Sources/go.sum
Source/App/AppConfiguration.swift
Source/Bot/Operations/SendMissionOperation.swift
Source/Controller/LaunchViewController.swift

This is a temporary fix for #847. It makes three changes:
- Planetary will connect to the the Planetary pubs if you have no other pubs or rooms to connect to, even if `joinedPlanetarySystem` option is false. This fixes the flow where you imported your key into Planetary. When importing a key we automatically set `joinedPlanetarySystem` to `false` to prevent auto-publishing of pub messages and forking your feed. However if you have no peers on your local network you have no one to download your own feed from. This should be a temporary fix until we can at least implement #874. Really we need to redo our whole imported key flow.
- Fixes go-ssb so that it correctly falls back to legacy gossip when a peer does not support EBTs.
- Prints the AppConfiguration details on launch for easier …

Fix legacy gossip

---

CHANGELOG.md
Frameworks/GoSSB.xcframework/Info.plist
Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/go.mod
GoSSB/Sources/go.sum
Source/App/AppConfiguration.swift
Source/Bot/Operations/SendMissionOperation.swift
Source/Controller/LaunchViewController.swift

This fixes a crash introduced in #877. It points go-ssb at https://github.com/planetary-social/ssb/pull/8 instead of https://github.com/planetary-social/ssb/pull/6.

Fix byte sink crash

---

.gitattributes
.github/workflows/main.yml

This changes the merge strategy for `CHANGELOG.md` so that we should have fewer conflicts in that file. Basically if two commits add lines to the changelog in the same place then by default it will just accept both lines rather than creating a conflict.
I also figured out how to fix the `Skip-Changelog` label thanks to [this comment](https://github.com/dangoslen/changelog-enforcer/issues/211#issuecomment-1255549336) on the issue I opened.

Changelog merge strategy

---

CHANGELOG.md
Source/UI/AvatarImageView.swift

Addresses #753 . 
To test, I used this image:
Right side shows the fix:

Fix avatar image aspect ratio

---

CHANGELOG.md
Shared/Extensions/UIViewController+Alert.swift
Source/Debug/DebugViewController.swift

This button was broken and I needed it for testing today. I think maybe it wasn't working because I was using DispatchQueue stuff inside a Task? I had to make some things @MainActor to get rid of the `DispatchQueue.main.async` stuff, and I ended up fixing some SwiftLint warnings too, which made the diff a little bigger.

Fix the share database button in debug settings

---

Analytics/Sources/Domain/Services/AnalyticsService.swift

Reverts planetary-social/planetary-ios#903
Seems to be breaking posthog

Revert "add type to posthog events to separate bot from user actions"

---

CHANGELOG.md
Planetary.xcodeproj/project.pbxproj
Pods/Pods.xcodeproj/project.pbxproj
Source/Controller/EditAboutViewController.swift
Source/UI/EditAboutView.swift
Source/UI/EditValueView.swift
Source/UI/TextFieldWithInsets.swift

As discussed in #460, I have changed the view to match the UI changes which include:
- The text area of the bio will covers the entire page
- The text inputs have rounded borders
- The text view for the bio will adapt to the keyboard when it shows up
| | |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/36312970/198868250-020cec67-34f5-4548-b788-82f38faf08ec.png" width="400" /> | <img src="https://user-images.githubusercontent.com/36312970/198868254-5a37c675-66b4-4e01-9d28-7d5bf1b3be70.png" width="400" /> |
| | | |
| --- | --- | --- |
| <img src="https://user-images.githubusercontent.com/36312970/198868338-ed780199-97f7-44b4-b79d-8f80189e929e.png" width="300" /> | <img src="https://user-images.githubusercontent.com/36312970/198868345-65875530-6e3f-4323-b177-6e96732fbacb …

Update the tap target on the Edit profile page

---

CONTRIBUTING.md

Add missing step installing Git LFS > `git lfs install` to allow pulling frameworks over git when cloning
Otherwise it fails showing something like this:
```
ld: warning: ignoring file ~/Library/Developer/Xcode/DerivedData/Planetary-fjsowinuoajswjaxifmsuhhptcol/Build/Products/Debug-iphonesimulator/libssb-go.a, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture x86_64:
"_ssbBlobsAdd", referenced from:
_$s9Planetary13GoBotInternalC8blobsAdd4data10completiony10Foundation4DataV_ySS_s5Error_pSgtctF in GoBotInternal.o
"_ssbBlobsWant", referenced from:
_$s9Planetary13GoBotInternalC9blobsWant3refySS_tKFySo10gostring_taXEfU_ …
```

Add missing step required before cloning the project to avoid build/run failures

---

Analytics/Sources/Delivery/Analytics+Bot.swift
CHANGELOG.md
Planetary.xcodeproj/project.pbxproj
Resources/Preload.bundle/Feeds/consolidatedFeed.json
Source/GoBot/GoBot.swift

We need to reduce how much we log from the bot to posthog. It's not useful. This is a simple thing which stops logging of the routine bot statuses. It doesn't stop the out of the ordinary things we'll want to track.

Reduce bot logging

---

UnitTests/ViewDatabaseTests.swift

This fixes the tests on `main`.

Bump maxAge for messages in ViewDatabasePreloadTests

---

Source/UI/FloatingButton.swift
Source/UI/Home/HomeView.swift
Source/UI/Message/MessageList.swift

Closes #1084 
Makes the floating button in HomeView functional again, and, as a bonus, scroll to top on tap.

Fix bug in FloatingButton where it wouldn't refresh the list

---

GoSSB/Sources/Makefile

We probably need a better fix in the future but for now I just added homebrew's bin dir to path.

Fix xcode can't find git-lfs

---

Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/go.mod
GoSSB/Sources/go.sum

Commits:
- 61064f466774e586ae0950c36f4c74a45018c166 Push blobs to peers (#211)
- 422b735c1d53062753e1d6207905046f02c46f7c Support blobs.get requests with "key" instead of "hash" (#213)

Bump scuttlego (6c4cdb2f3eb4 -> 422b735c1d53)

---

Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/go.mod
GoSSB/Sources/go.sum

Commits:
- ab28d505e4cacbd2f8a8f2c5cd7eab50b5a709ad Remove an unnecessary pointer
- 66a808ea0abf5f2668a1438dad3eda63493c3755 Make useful types in transport public
- 386f10b9743bcc163b016eb38c9be3e7a0e08185 Change package to a test package
- 688b2ceb45dab10df6cccb2224a59fa87a3e025a Make log debugger handle invalid UTF-8
- d6d5d269bda656b7b8e2c853b3b65a8bf6c3bf71 Fix handling duplicate sequences in message buffer

Bump github.com/planetary-social/scuttlego (422b735c1d53 -> d6d5d269bda6)

---

Frameworks/GoSSB.xcframework/Info.plist
Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/Makefile

Otherwise the files show up as modified when built from different commits even if they should be identical.

Don't include VCS info in builds

---

Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/debug.go
Source/GoBot/GoBotInternal.swift

- Removed unused fields: PID, Blobs, Root, Indices.
- Made peer information easier to parse by replacing multiserver address with two separate fields: publicKey and address.
- In effect simplified Swift code.
New data format:
{
"peers": [
{
"publicKey": "<string depicting base64-encoded raw public key>",
"address": "1.2.3.4:8000"
}
]
}

Cleanup types returned by ssbBotStatus

---

Frameworks/GoSSB.xcframework/Info.plist
Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/bindings/bindings.go
Source/GoBot/GoBot.swift
Source/GoBot/GoBotInternal.swift

- removed ServicePubs and ViewDBSchemaVersion as they were unused
- renamed "app key" to "network key" for readability
- changed "hops" so that they are interpreted like in other clients/scuttlego
- made all keys lowercase to follow conventions

Cleanup config

---

Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/go.mod
GoSSB/Sources/go.sum

d6d5d269bda6 -> 4e9568c70477
Commits:
- 8fe4de7be4a709a87a23af556402cc693d5ce20b Improve message buffer logging
- 7a5daf8ce5a0276dbed3b6dcac1a3ac60750169b Fix default hops value
- 972ed33bf3145cf6112cca4f2b75740211035535 Move the code creating wanted feeds to application
- ae4b30f6441535d78ec8c55c8be79e2c35fc1221 Update contributing documentation
- 5a5d6404665c760bd8cc1cd3ec0357a0f746c520 Don't replicate forked feeds with peers who have them
- 46c35fd6e213cb38e6149e4d0860353d57ab4c50 Avoid loading the entire feed just to get the sequence
- 4e9568c70477d58a1f0ca61aeef246434fa3aeeb Do not perform writes when listing want lists

Bump github.com/planetary-social/scuttlego

---

Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/api-ios.go
Source/GoBot/GoBotInternal.swift

Trace logging can be enabled by changing "testing" to true in the configuration. This is the only thing that is currently controlled by the testing parameter. I changed the config so this is not automatic as logging at this level really produces a lot of data.

Make it easier to enable trace logging

---

Source/GoBot/GoBot.swift

This might fix #1192. My theory for what is happening is that the `guessIsRestoring()` function thought we were restoring because forked feed protection was tripped because the scuttlego migration fixed my soft fork. I removed the early exit on blob loading if we think the user is restoring their feed. This was an optimization but maybe we don't need it anymore on scuttlego. 
I think there may be some other issue where my name isn't loading at first on every app launch which is weird. I posted about that here. https://planetary-app.slack.com/archives/CE6RE7ND6/p1677697080087179

Maybe fix blobs not loading sometimes

---

Frameworks/GoSSB.xcframework/Info.plist
Frameworks/GoSSB.xcframework/ios-arm64/libssb-go.a
Frameworks/GoSSB.xcframework/ios-arm64_x86_64-simulator/libssb-go.a
GoSSB/Sources/streams.go
Planetary.xcodeproj/project.pbxproj
Source/GoBot/GoBot.swift
Source/GoBot/GoBotInternal.swift
Source/Model/Message.swift
Source/Model/ReceiveLogMessage.swift
UnitTests/GoBotOrderedTests.swift
UnitTests/Resources/Feed_big.json
UnitTests/Resources/Feed_example.json
UnitTests/Resources/Feed_example_preload.json
UnitTests/Resources/MessageWithReceivedSeq.json
UnitTests/Resources/RoomAliasAnnouncement_registered.json
UnitTests/Resources/RoomAliasAnnouncement_revoked.json

We had strong coupling to models used by Swift so I had to introduce a new model to clean things up. My initial goal was to remove `timestamp` and `HashedKey` from `logEntry`. I checked that the hashes calculated in Swift was identical to the ones that Go returned.
So now messages returned from receive log look like this and don't contain the timestamp and the hashed key:
```
{
"key":"%something.sha256",
"value":{
"previous":"%XphMUkWQtomKjXQvFGfsGYpt69sgEY7Y4Vou9cEuJho=.sha256",
"author":"@FCX/tsDLpubCPKKfIrw4gc+SQkHcaD17s7GI6i/ziWY=.ed25519",
"sequence":2,
"timestamp":1514517078157,
"hash":"sha256",
"content":{
"type":"post",
"text":"Second post!"
}
},
"receiveLogSequence":1234
}
```

Create a separate model for data returned by scuttlego

---

UnitTests/GoBotIntegrationTests.swift

This was disabled due to failures related to go-ssb. Scuttlego should not fail like this and if it does it needs to be fixed.

Reenable testLoginLogoutLoop
